# Generated by Django 5.1.3 on 2026-02-27 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilSolicitante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_solicitante",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome do solicitante"
                    ),
                ),
                (
                    "banco",
                    models.CharField(blank=True, max_length=100, verbose_name="Banco"),
                ),
                (
                    "agencia",
                    models.CharField(blank=True, max_length=20, verbose_name="Agência"),
                ),
                (
                    "conta_tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CORRENTE", "Conta Corrente"),
                            ("POUPANCA", "Poupança"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de conta",
                    ),
                ),
                (
                    "conta_numero",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="Conta Corrente ou Poupança",
                    ),
                ),
                (
                    "chave_pix",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Chave PIX"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_solicitante",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil do solicitante",
                "verbose_name_plural": "Perfis dos solicitantes",
            },
        ),
    ]
