# Generated by Django 5.1.3 on 2026-02-27 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0002_solicitacao_reembolso"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemReembolso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_despesa",
                    models.CharField(max_length=30, verbose_name="Tipo de despesa"),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Descrição"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="KM (deslocamento)",
                    ),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="intra.solicitacaoreembolso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de reembolso",
                "verbose_name_plural": "Itens de reembolso",
            },
        ),
    ]
