# Generated by Django 5.1.3 on 2026-02-27 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0003_item_reembolso"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="aprovado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da decisão"
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="aprovado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reembolsos_aprovados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="motivo_rejeicao",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Motivo da rejeição"
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("APROVADO", "Aprovado"),
                    ("REJEITADO", "Rejeitado"),
                ],
                default="PENDENTE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
