# Generated by Django 5.1.3 on 2026-02-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0005_grupo_gestor_administrativo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="solicitacaoreembolso",
            options={
                "ordering": ["-criado_em"],
                "permissions": [
                    (
                        "pode_aprovar_reembolso",
                        "Pode aprovar/rejeitar solicitações de reembolso (Gestor Administrativo)",
                    )
                ],
                "verbose_name": "Solicitação de reembolso",
                "verbose_name_plural": "Solicitações de reembolso",
            },
        ),
    ]
