# Generated by Django 5.1.3 on 2026-03-03 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0006_permissao_gestor_reembolso"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="solicitacaoreembolso",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Solicitação de reembolso",
                "verbose_name_plural": "Solicitações de reembolso",
            },
        ),
        migrations.CreateModel(
            name="RegraUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("gestor_administrativo", "Gestor Administrativo")],
                        max_length=50,
                        verbose_name="Tipo de permissionamento",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regras_usuario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regra de usuário",
                "verbose_name_plural": "Regras de usuários",
                "unique_together": {("user", "role")},
            },
        ),
    ]
