# Generated by Django 4.2.27 on 2026-03-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0007_regra_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemreembolso",
            name="cod_despesa",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Código de despesa"
            ),
        ),
        migrations.AddField(
            model_name="itemreembolso",
            name="data_despesa",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da despesa"
            ),
        ),
    ]
