# Generated by Django 4.2.27 on 2026-03-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0008_itemreembolso_cod_despesa_itemreembolso_data_despesa"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilsolicitante",
            name="email_gestor",
            field=models.EmailField(
                blank=True, max_length=200, verbose_name="E-mail do gestor"
            ),
        ),
        migrations.AddField(
            model_name="perfilsolicitante",
            name="nome_gestor",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nome do gestor"
            ),
        ),
    ]
