# Generated by Django 4.2.27 on 2026-03-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0009_perfilsolicitante_email_gestor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemreembolso",
            name="anexo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="reembolsos/anexos/",
                verbose_name="Anexo",
            ),
        ),
    ]
