# Generated by Django 4.2.27 on 2026-03-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0010_itemreembolso_anexo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CentroCusto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "PROGRAMA",
                    models.CharField(blank=True, max_length=150000, null=True),
                ),
                ("CODIGO", models.CharField(blank=True, max_length=150000, null=True)),
                (
                    "DESCRICAO",
                    models.CharField(blank=True, max_length=150000, null=True),
                ),
            ],
        ),
    ]
