# Generated by Django 5.2.12 on 2026-03-09 16:12

import django.db.models.deletion
import intra.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0011_centrocusto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="aprovado_em_gestor",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da decisão do gestor"
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="aprovado_em_gestor_admin",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Data da decisão do gestor administrativo",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="aprovado_por_gestor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reembolsos_aprovados_gestor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="aprovado_por_gestor_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reembolsos_aprovados_gestor_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="motivo_rejeicao_gestor",
            field=models.CharField(
                blank=True,
                max_length=500,
                verbose_name="Motivo da rejeição pelo gestor",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="motivo_rejeicao_gestor_admin",
            field=models.CharField(
                blank=True,
                max_length=500,
                verbose_name="Motivo da rejeição pelo gestor administrativo",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="status_gestor",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("APROVADO", "Aprovado"),
                    ("REJEITADO", "Rejeitado"),
                ],
                default="PENDENTE",
                max_length=20,
                verbose_name="Status do Gestor",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="status_gestor_admin",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("APROVADO", "Aprovado"),
                    ("REJEITADO", "Rejeitado"),
                ],
                default="PENDENTE",
                max_length=20,
                verbose_name="Status do Gestor Administrativo",
            ),
        ),
        migrations.AlterField(
            model_name="itemreembolso",
            name="anexo",
            field=models.FileField(
                blank=True,
                null=True,
                storage=intra.models.MediaStorage(),
                upload_to="reembolsos/anexos/",
                verbose_name="Anexo",
            ),
        ),
        migrations.AlterField(
            model_name="regrausuario",
            name="role",
            field=models.CharField(
                choices=[
                    ("gestor", "Gestor"),
                    ("gestor_administrativo", "Gestor Administrativo"),
                ],
                max_length=50,
                verbose_name="Tipo de permissionamento",
            ),
        ),
    ]
