# Generated by Django 5.2.12 on 2026-03-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0012_solicitacaoreembolso_aprovado_em_gestor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="concluido",
            field=models.BooleanField(
                default=False,
                help_text="Marcado quando o gestor administrativo conclui a solicitação",
                verbose_name="Concluído",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="concluido_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da conclusão"
            ),
        ),
    ]
