# Generated by Django 5.2.12 on 2026-03-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0013_solicitacaoreembolso_concluido_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="envelope_id_docusign",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="ID do Envelope DocuSign",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="status_docusign",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Status da Assinatura DocuSign",
            ),
        ),
    ]
