# Generated by Django 5.2.12 on 2026-03-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0014_solicitacaoreembolso_envelope_id_docusign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="forma_pagamento",
            field=models.CharField(
                blank=True,
                choices=[("PIX", "PIX"), ("TRANSFERENCIA", "Transferência Bancária")],
                max_length=20,
                null=True,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="pix_banco",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Banco (PIX)"
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="pix_chave",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Chave PIX"
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="pix_cpf",
            field=models.CharField(
                blank=True, max_length=14, null=True, verbose_name="CPF (PIX)"
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="transf_agencia",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Agência (Transferência)",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="transf_banco",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Banco (Transferência)",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="transf_conta_numero",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Conta (Transferência)",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="transf_conta_tipo",
            field=models.CharField(
                blank=True,
                choices=[("CORRENTE", "Conta Corrente"), ("POUPANCA", "Poupança")],
                max_length=10,
                null=True,
                verbose_name="Tipo de Conta (Transferência)",
            ),
        ),
    ]
