# Generated by Django 5.2.12 on 2026-03-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0015_adicionar_campos_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="nome_gestor",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nome do Gestor"
            ),
        ),
    ]
