# Generated by Django 5.2.12 on 2026-03-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0016_solicitacaoreembolso_nome_gestor"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilsolicitante",
            name="banco_pix",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Banco (PIX)"
            ),
        ),
        migrations.AddField(
            model_name="perfilsolicitante",
            name="cpf_pix",
            field=models.CharField(blank=True, max_length=14, verbose_name="CPF (PIX)"),
        ),
        migrations.AddField(
            model_name="perfilsolicitante",
            name="cpf_transferencia",
            field=models.CharField(
                blank=True, max_length=14, verbose_name="CPF (Transferência)"
            ),
        ),
        migrations.AddField(
            model_name="perfilsolicitante",
            name="forma_pagamento",
            field=models.CharField(
                blank=True,
                choices=[("PIX", "PIX"), ("TRANSFERENCIA", "Transferência Bancária")],
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
    ]
