# Generated by Django 5.2.12 on 2026-03-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0017_perfilsolicitante_banco_pix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="pago",
            field=models.BooleanField(
                default=False,
                help_text="Marcado quando o gestor administrativo marca como pago",
                verbose_name="Pago",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="pago_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data do pagamento"
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoreembolso",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("APROVADO", "Aprovado"),
                    ("REJEITADO", "Rejeitado"),
                    ("AGUARDANDO_PAGAMENTO", "Aprovado - Aguardando pagamento"),
                    ("PAGO_AGUARDANDO_ASSINATURAS", "Pago - Aguardando assinaturas"),
                    ("ASSINADO_TODAS_PARTES", "Assinado por todas as partes"),
                ],
                default="PENDENTE",
                max_length=50,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoreembolso",
            name="status_gestor",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("APROVADO", "Aprovado"),
                    ("REJEITADO", "Rejeitado"),
                    ("AGUARDANDO_PAGAMENTO", "Aprovado - Aguardando pagamento"),
                    ("PAGO_AGUARDANDO_ASSINATURAS", "Pago - Aguardando assinaturas"),
                    ("ASSINADO_TODAS_PARTES", "Assinado por todas as partes"),
                ],
                default="PENDENTE",
                max_length=50,
                verbose_name="Status do Gestor",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoreembolso",
            name="status_gestor_admin",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("APROVADO", "Aprovado"),
                    ("REJEITADO", "Rejeitado"),
                    ("AGUARDANDO_PAGAMENTO", "Aprovado - Aguardando pagamento"),
                    ("PAGO_AGUARDANDO_ASSINATURAS", "Pago - Aguardando assinaturas"),
                    ("ASSINADO_TODAS_PARTES", "Assinado por todas as partes"),
                ],
                default="PENDENTE",
                max_length=50,
                verbose_name="Status do Gestor Administrativo",
            ),
        ),
    ]
