# Generated by Django 5.2.12 on 2026-03-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0018_solicitacaoreembolso_pago_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="data_pagamento_programada",
            field=models.DateField(
                blank=True,
                help_text="Data programada para o pagamento pelo gestor administrativo",
                null=True,
                verbose_name="Data de pagamento programada",
            ),
        ),
    ]
