# Generated by Django 5.2.12 on 2026-03-12 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0019_solicitacaoreembolso_data_pagamento_programada"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoReembolso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acao", models.CharField(max_length=100, verbose_name="Ação")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data"),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="intra.solicitacaoreembolso",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historico_reembolsos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de reembolso",
                "verbose_name_plural": "Históricos de reembolsos",
                "ordering": ["-criado_em"],
            },
        ),
    ]
