# Generated by Django 5.2.12 on 2026-03-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0021_add_status_pagamento_agendado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacaoreembolso",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("APROVADO", "Aprovado"),
                    ("REJEITADO", "Rejeitado"),
                    ("AGUARDANDO_PAGAMENTO", "Aprovado - Aguardando pagamento"),
                    ("PAGAMENTO_AGENDADO", "Solicitação aprovada - Pagamento agendado"),
                    ("PAGO_AGUARDANDO_ASSINATURAS", "Pago - Aguardando assinaturas"),
                    ("ASSINADO_TODAS_PARTES", "Assinado por todas as partes"),
                    ("CONCLUIDO", "Concluído"),
                ],
                default="PENDENTE",
                max_length=50,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoreembolso",
            name="status_gestor",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("APROVADO", "Aprovado"),
                    ("REJEITADO", "Rejeitado"),
                    ("AGUARDANDO_PAGAMENTO", "Aprovado - Aguardando pagamento"),
                    ("PAGAMENTO_AGENDADO", "Solicitação aprovada - Pagamento agendado"),
                    ("PAGO_AGUARDANDO_ASSINATURAS", "Pago - Aguardando assinaturas"),
                    ("ASSINADO_TODAS_PARTES", "Assinado por todas as partes"),
                    ("CONCLUIDO", "Concluído"),
                ],
                default="PENDENTE",
                max_length=50,
                verbose_name="Status do Gestor",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoreembolso",
            name="status_gestor_admin",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("APROVADO", "Aprovado"),
                    ("REJEITADO", "Rejeitado"),
                    ("AGUARDANDO_PAGAMENTO", "Aprovado - Aguardando pagamento"),
                    ("PAGAMENTO_AGENDADO", "Solicitação aprovada - Pagamento agendado"),
                    ("PAGO_AGUARDANDO_ASSINATURAS", "Pago - Aguardando assinaturas"),
                    ("ASSINADO_TODAS_PARTES", "Assinado por todas as partes"),
                    ("CONCLUIDO", "Concluído"),
                ],
                default="PENDENTE",
                max_length=50,
                verbose_name="Status do Gestor Administrativo",
            ),
        ),
    ]
