# Generated by Django 5.2.12 on 2026-03-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0022_add_status_concluido"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoreembolso",
            name="transf_cpf",
            field=models.CharField(
                blank=True,
                max_length=18,
                null=True,
                verbose_name="CPF/CNPJ (Transferência)",
            ),
        ),
        migrations.AlterField(
            model_name="perfilsolicitante",
            name="cpf_pix",
            field=models.CharField(
                blank=True, max_length=18, verbose_name="CPF/CNPJ (PIX)"
            ),
        ),
        migrations.AlterField(
            model_name="perfilsolicitante",
            name="cpf_transferencia",
            field=models.CharField(
                blank=True, max_length=18, verbose_name="CPF/CNPJ (Transferência)"
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoreembolso",
            name="pix_cpf",
            field=models.CharField(
                blank=True, max_length=18, null=True, verbose_name="CPF/CNPJ (PIX)"
            ),
        ),
    ]
