# Generated by Django 5.2.13 on 2026-05-18

import intra.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0023_adicionar_cpf_cnpj_suporte"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemreembolso",
            name="anexo",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                storage=intra.models.MediaStorage(),
                upload_to=intra.models.anexo_reembolso_upload_to,
                verbose_name="Anexo",
            ),
        ),
    ]
