# Generated by Django 5.2.12 on 2026-05-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intra", "0024_itemreembolso_anexo_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemreembolso",
            name="cod_despesa",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Código no orçamento"
            ),
        ),
        migrations.AlterField(
            model_name="itemreembolso",
            name="descricao",
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name="solicitacaoreembolso",
            name="cod_despesa",
            field=models.CharField(max_length=50, verbose_name="Código no orçamento"),
        ),
    ]
